# Generated by Django 4.0.2 on 2022-03-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_projects_project'),
        ('users', '0002_contributors'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contributors',
            new_name='Contributor',
        ),
    ]
