# Generated by Django 4.0.2 on 2022-03-11 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_contributor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('Author', 'Author'), ('Contributor', 'Contributor')], max_length=128),
        ),
    ]
