# Generated by Django 4.0.2 on 2022-03-04 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_contributors_contributor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contributor',
            name='permission',
        ),
        migrations.AlterField(
            model_name='contributor',
            name='role',
            field=models.CharField(choices=[('A', 'Auteur'), ('C', 'Contributeur')], max_length=128),
        ),
    ]
