# Generated by Django 4.0.2 on 2022-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0003_alter_issue_assignee_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('Faible', 'Faible'), ('Moyenne', 'Moyenne'), ('Elevée', 'Elevée')], max_length=64),
        ),
        migrations.AlterField(
            model_name='issue',
            name='status',
            field=models.CharField(choices=[('A faire', 'A faire'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], max_length=64),
        ),
        migrations.AlterField(
            model_name='issue',
            name='tag',
            field=models.CharField(choices=[('Bug', 'Bug'), ('Amélioration', 'Amélioration'), ('Tâche', 'Tâche')], max_length=64),
        ),
    ]
