# Generated by Django 4.0.2 on 2022-03-12 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0004_alter_issue_priority_alter_issue_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='priority',
            field=models.CharField(choices=[('L', 'Low'), ('M', 'Middle'), ('H', 'High')], max_length=64),
        ),
    ]
