# Generated by Django 4.0.2 on 2022-03-08 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('Back End', 'Back End'), ('Front End', 'Front End'), ('IOS', 'IOS'), ('Android', 'Android')], max_length=64)),
            ],
            options={
                'unique_together': {('title', 'type')},
            },
        ),
    ]
