# Generated by Django 4.0.2 on 2022-03-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('description', models.TextField(blank=True, max_length=128)),
                ('type', models.CharField(choices=[('BE', 'Back End'), ('FE', 'Front End'), ('IOS', 'IOS'), ('A', 'Android')], max_length=64)),
            ],
        ),
        migrations.DeleteModel(
            name='Issue',
        ),
    ]
