# Generated by Django 4.0.2 on 2022-03-03 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0002_rename_comments_comment_rename_issues_issue'),
        ('users', '0002_contributors'),
        ('projects', '0002_projects_delete_issue'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Projects',
            new_name='Project',
        ),
    ]
