# Generated by Django 4.0.2 on 2022-03-04 12:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_rename_projects_project'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='project',
            unique_together={('title', 'type')},
        ),
    ]
