# Generated by Django 4.0.2 on 2022-03-07 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0004_alter_project_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.CharField(choices=[('Back End', 'Back End'), ('Front End', 'Front End'), ('IOS', 'IOS'), ('Android', 'Android')], max_length=64),
        ),
    ]
